server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

  client:
    register-with-eureka: false
    fetch-registry: false

    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME:localhost}:${server.port}/eureka/

  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.netflix.eureka: INFO
    org.springframework.cloud.netflix.eureka: INFO