export const DEMO_JOBS = [
  {
    id: "1",
    title: "Senior Java Developer",
    company: "TechCorp India",
    location: "Hyderabad",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    salaryMin: 1200000,
    salaryMax: 2000000,
    skills: ["Java 17", "Spring Boot", "Microservices", "PostgreSQL", "Docker", "Redis"],
    isRemote: false,
    createdAt: "2026-05-10",
    postedAt: "2026-05-10",
    status: "ACTIVE",
    description: `We are looking for a Senior Java Developer to join our growing
engineering team. You will design and build scalable backend microservices.`,
    requirements: [
      "5+ years Java experience",
      "Strong Spring Boot & Spring Security knowledge",
      "Microservices architecture experience",
      "PostgreSQL and Redis proficiency",
      "Docker and Kubernetes familiarity",
    ],
    applicationDeadline: "2026-06-30",
  },
  {
    id: "2",
    title: "React Frontend Engineer",
    company: "StartupXYZ",
    location: "Bangalore",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    salaryMin: 800000,
    salaryMax: 1400000,
    skills: ["React", "TypeScript", "Tailwind CSS", "Redux", "REST APIs"],
    isRemote: true,
    createdAt: "2026-05-11",
    postedAt: "2026-05-11",
    status: "ACTIVE",
    description: "Build beautiful, performant UIs used by thousands of users daily.",
    requirements: [
      "3+ years React experience",
      "TypeScript proficiency",
      "Experience with Redux or Zustand",
      "Tailwind CSS knowledge",
    ],
    applicationDeadline: "2026-06-15",
  },
  {
    id: "3",
    title: "DevOps Engineer",
    company: "CloudSystems",
    location: "Remote",
    jobType: "REMOTE",
    experienceLevel: "MID",
    salaryMin: 1000000,
    salaryMax: 1800000,
    skills: ["AWS", "Docker", "Kubernetes", "Jenkins", "Terraform", "Linux"],
    isRemote: true,
    createdAt: "2026-05-12",
    postedAt: "2026-05-12",
    status: "ACTIVE",
    description: "Own our cloud infrastructure and CI/CD pipelines.",
    requirements: [
      "3+ years DevOps experience",
      "Strong AWS knowledge",
      "Docker and Kubernetes hands-on",
      "Terraform infrastructure-as-code",
    ],
    applicationDeadline: "2026-06-20",
  },
  {
    id: "4",
    title: "Full Stack Developer Intern",
    company: "InnovateTech",
    location: "Pune",
    jobType: "INTERNSHIP",
    experienceLevel: "ENTRY",
    salaryMin: 20000,
    salaryMax: 40000,
    skills: ["React", "Node.js", "MongoDB"],
    isRemote: false,
    createdAt: "2026-05-09",
    postedAt: "2026-05-09",
    status: "ACTIVE",
    description: "Work with the product team across frontend and backend features.",
    requirements: ["React basics", "Node.js basics", "Good problem-solving skills"],
    applicationDeadline: "2026-06-10",
  },
  {
    id: "5",
    title: "Backend Engineer - Python",
    company: "DataFlow Inc",
    location: "Chennai",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    salaryMin: 900000,
    salaryMax: 1500000,
    skills: ["Python", "FastAPI", "PostgreSQL", "Redis"],
    isRemote: false,
    createdAt: "2026-05-08",
    postedAt: "2026-05-08",
    status: "ACTIVE",
    description: "Build reliable APIs and data workflows for analytics products.",
    requirements: ["Python API experience", "PostgreSQL knowledge", "Redis experience"],
    applicationDeadline: "2026-06-18",
  },
  {
    id: "6",
    title: "Cloud Architect",
    company: "GlobalTech",
    location: "Mumbai",
    jobType: "CONTRACT",
    experienceLevel: "LEAD",
    salaryMin: 2500000,
    salaryMax: 4000000,
    skills: ["AWS", "Azure", "Terraform", "K8s"],
    isRemote: true,
    createdAt: "2026-05-07",
    postedAt: "2026-05-07",
    status: "ACTIVE",
    description: "Design cloud architecture for large-scale enterprise systems.",
    requirements: ["Cloud architecture experience", "Terraform", "Kubernetes"],
    applicationDeadline: "2026-06-25",
  },
];

export const findDemoJob = (id) => DEMO_JOBS.find((job) => job.id === String(id));
